Set up a west workspace
This should address the following issue:
FATAL ERROR: no west workspace found.
"west update" requires one.

Signed-off-by: Jannis Ruellmann <jannis.ruellmann@gmail.com>